Portfolio Website
Alidragos/Portofolio pull request #3
Opened 2022-04-26 12:25 UTC by Alidragos

## Hello Microverse
# This is a simple project personal Portfolio website that will be interesting:
# I did the following:
- Modify the index.html andstyle.css

2022-04-26 12:32 UTC, williamrolando88 reviewed
Hi @Alidragos, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have an appropriate Readme file, please use this [template](https://github.com/microverseinc/readme-template)



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-26 14:49 UTC, ShadyShawkat requested changes
## Hi @Alidragos, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 14:49 UTC, ShadyShawkat commented on README.md
> +### Deployment
- [x] Please be sure to remove the unwanted sections of your readme.

2022-04-26 14:49 UTC, ShadyShawkat commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
- [x] Good job providing your social links 👏🏻. Please remove the second author's placeholder for now.

2022-04-26 14:49 UTC, ShadyShawkat commented on index.html
> +      </div>
- [ ] Kindly replace this `div` tag with a `nav` tag for semantic purposes.

2022-04-26 14:49 UTC, ShadyShawkat commented on index.html
> +    <div class="box box2">
- [ ] Let's replace the `div` wrapper for this section to be a `header` tag instead, for semantic purposes.

2022-04-26 14:49 UTC, ShadyShawkat commented on index.html
> +    </div>
- [ ] Please replace the `div` wrapper of this section to be a `section` tag for semantic purposes.

2022-04-26 14:49 UTC, ShadyShawkat commented on index.html
> +        <br>  you need coded, don't hesitate to contact <br><br> me.</p>
- [ ] [OPTIONAL] Consider removing the `br` tags around each phrase in this paragraph. You're better off having one big paragraph and you can control its width, padding, margin, ..etc.

2022-04-26 14:49 UTC, ShadyShawkat commented on index.html
> +       <a href="#home" class="active"><i class="fa fa-medium" aria-hidden="true"></i></a>
- [ ] Please wrap the social media links with an `ul` tag each. You can use something like the following:
```
<ul>
   <li>
      <a>
         <img> first link
      </a>
   </li>
   <li>
      <a>
         <img> second link
      </a>
   </li>
   ...
</ul>
```

2022-04-26 14:49 UTC, ShadyShawkat commented on index.html
>  </body>
- Please try to stick as much as possible to the Figma design as per project requirement, which includes:
   - [ ] Adjusting the colors of the body and text (logo text and "let's connect" text) to match the Figma design.
   - [ ] Adding the background of this section provided by the Figma design, and please make sure it's fitted to this section correctly.
   - [ ] Using the same font family (which is "Poppins" here) to match the Figma design.
   - [ ] Adjusting the spacing around each element to match the Figma design.
   - [ ] Removing the space around the header section (highlighted with red lines below), to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/165325586-57faf2cb-6318-4f49-ad53-e68e0d2aef23.png) | ![image](https://user-images.githubusercontent.com/62290545/165319939-97f7fbdb-c8ec-4e71-95d6-f942bd15f3b1.png) |

2022-04-27 07:57 UTC, prolajumokeoni requested changes
Hi @Alidragos 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good Readme

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_Check inline comments_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 07:57 UTC, prolajumokeoni commented on index.html
> +        </div>
- [ ] Good job wrapping the hamburger menu in a nav tag, kindly replace the div tag wrapping the logo and hamburger  menu with a header tag, this makes your website more semantic and easily readable by browsers, 
- [ ] Kindly delete the `margin-top: 60px` before the header as this will make your portfolio look more like the Figma design
-  Please implement all  these as the previous reviewer also requested this changes 🤗 👍🏿

2022-04-27 07:57 UTC, prolajumokeoni commented on index.html
> +        </section>
Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Template 1-Mobile-Main](https://user-images.githubusercontent.com/69638013/165468300-7a6ba05b-1547-4195-bae6-37784ffa0d48.png)  | ![Screenshot_85](https://user-images.githubusercontent.com/69638013/165468322-aba5f436-8a63-43fd-9142-2e3d22a6b5c0.png)

- [ ]  Kindly align all social media icons to the left they should look similar to the  Figma design 👍🏿 

- [ ] Kindly make the h1 header the biggest text in your page, just as you had it in the previous review 👍🏿 

### OPTIONAL



- [ ] Kindly add the background image with CSS and not the img tag, please add this as it was missed by the previous reviewer 👍🏿

2022-04-27 10:39 UTC, Alidragos commented on index.html
> +        </section>
Hi @prolajumokeoni,
I am not clear on what to do for the optional review background image with CSS and not the img tag. 
Thank you.

2022-04-27 11:09 UTC, aimemalaika requested changes
Hi @Alidragos, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 11:09 UTC, aimemalaika commented on index.html
> +            </div>
- [ ] Kindly try to replicate the exact Figma design by adding the missing background image
Check the Figma design
<img width="188" alt="Screen Shot 2022-04-27 at 12 57 48" src="https://user-images.githubusercontent.com/28307960/165503855-ac04c3c9-2395-40f1-a836-800462b12619.png">

2022-04-27 11:09 UTC, aimemalaika commented on index.html
> +                <h4>Let's connect</h4>
- [ ] Kindly make sure this is a link or a button as stated in the requirements

2022-04-27 11:09 UTC, aimemalaika commented on styles.css
> +}
- [ ] Kindly use flex property instead of `inline`

2022-04-27 11:09 UTC, aimemalaika commented on index.html
> +        </div>
- [ ] Kindly use `Header` instead of a generic div as it is the proper semantic tag

2022-04-27 12:36 UTC, Alidragos commented on index.html
> +                <h4>Let's connect</h4>
This is a text. Let's connect.

2022-04-27 14:29 UTC, Alidragos commented on index.html
> +            </div>
I do have the background image from fatima, so I commented out and then put the background colour of the image. I hope this is what I have to do. Thank you.

2022-04-27 15:14 UTC, Ismailco requested changes
### Hi @Alidragos,

Great work on making some of the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [x] Please stick to the design as much as possible (e.g. font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

 - Your design:
 
![Screenshot_20220427_150922](https://user-images.githubusercontent.com/25227022/165551688-eea4622e-3d67-41b4-b26e-994049557a8a.png)



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 15:14 UTC, Ismailco commented on index.html
>      <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crosso
- [x] [OPTIONAL] Unnecessary comments make your code messy, kindly remove this commented block of code

2022-04-27 15:14 UTC, Ismailco commented on index.html
> +        <section class="box box2">
- [ ] Your page doesn't have a background image, as the previous reviewer suggested kindly try to add the messing background image
[Check the Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

2022-04-27 15:14 UTC, Ismailco commented on index.html
> +            <h4>LET’S CONNECT</h4>
- [x] You didn't implement the change by the last reviewer, you can use ```<a href="#">``` tag to make this text a link

2022-04-27 19:31 UTC, koomekevo approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: 
Hi @Alidragos, 

<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: You have demonstrated **determination** in implementing the changes of the previous reviewers to your level best.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 19:36 UTC, merged

2022-04-27 19:36 UTC, Alidragos commented
Thank you.